language: ruby
script:
  - bundle exec mspec -V -fs -t ruby
branches:
  only:
    - ruby
notifications:
  email: false
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ruby-head
#  - jruby-18mode
#  - jruby-19mode
#  - jruby-head
#  - rbx-18mode
#  - rbx-19mode
#  - rbx-head
#  - ree
#jdk:
#  - oraclejdk7
matrix:
 allow_failures:
  - rvm: jruby-18mode
  - rvm: jruby-19mode
  - rvm: jruby-head
  - rvm: rbx-18mode
  - rvm: rbx-19mode
  - rvm: rbx-head
  - rvm: ree
