sudo: false
language: ruby
install:
  - git clone https://github.com/ruby/mspec.git ../mspec
script:
  - ../mspec/bin/mspec
matrix:
  include:
    - rvm: 2.1.10
    - rvm: 2.2.6
    - rvm: 2.3.3
    - rvm: 2.4.0
    - rvm: ruby-head
branches:
  only:
    - master
    - /^try/
notifications:
  email:
    on_success: change
    on_failure: change
