language: ruby
script: bundle exec mspec .
rvm:
  - 2.1
  - ruby-head
  - rbx-2
  - jruby
  - jruby-head
matrix:
  allow_failures:
   - rvm: ruby-head
   - rvm: rbx-2
   - rvm: jruby
   - rvm: jruby-head
notifications:
  recipients:
    - brixen@gmail.com
  irc:
    channels:
      - "chat.freenode.net#rubyspec"
    on_success: change
    on_failure: change
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
