language: ruby
script:
  - bundle exec mspec .
rvm:
  - ruby-head
  - rbx-head
allow_failures:
 - rvm: ruby-head
 - rvm: rbx-head
notifications:
  recipients:
    - brixen@gmail.com
  irc:
    channels:
      - "chat.freenode.net#rubyspec"
    on_success: change
    on_failure: change
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
